/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.sports.portlet.tournament.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.sports.portlet.tournament.model.Tournament;
import com.sports.portlet.tournament.service.TournamentLocalServiceUtil;

/**
 * The extended model base implementation for the Tournament service. Represents a row in the &quot;sports_tournament&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TournamentImpl}.
 * </p>
 *
 * @author vijayan.chendrayan
 * @see TournamentImpl
 * @see com.sports.portlet.tournament.model.Tournament
 * @generated
 */
public abstract class TournamentBaseImpl extends TournamentModelImpl
	implements Tournament {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tournament model instance should use the {@link Tournament} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			TournamentLocalServiceUtil.addTournament(this);
		}
		else {
			TournamentLocalServiceUtil.updateTournament(this);
		}
	}
}